// 迁移自 DeerFlow frontend/src/components/workspace/messages/markdown-link.tsx；许可见 src/markdown/DEERFLOW-LICENSE。
// Mini 使用普通链接；不接入 DeerFlow 专属引用卡片和 /mnt 文件路由。
import type { AnchorHTMLAttributes } from "react";

import { cn } from "../lib/utils";

import type { ExtraProps } from "streamdown";

/**
 * Schemes we are willing to render as a navigable ``<a href=...>``.
 *
 * Anything else (``javascript:``, ``data:text/html``, ``vbscript:``,
 * ``file:``, …) is blocked because once it lands in a real anchor the
 * browser happily executes the payload in the chat surface where
 * sessionStorage / CSRF cookies are reachable. We accept ``http(s)``
 * plus the non-executing ``mailto:`` / ``tel:`` schemes; same-origin
 * absolute paths (``/…``), scheme-less relative references (``report.md``,
 * ``./…``, ``../…``), and in-document anchors (``#…``) are also allowed
 * — they all resolve under the current HTTP(S) origin.
 */
const SAFE_HREF_PROTOCOLS = ["http:", "https:", "mailto:", "tel:"] as const;

export function isSafeHref(href: string | undefined): boolean {
  if (typeof href !== "string" || href.length === 0) {
    return false;
  }
  // Same-document anchors (e.g. "#section").
  if (href.startsWith("#")) {
    return true;
  }
  // Protocol-relative URLs (//evil.com/path) would inherit the current
  // page's scheme and navigate to an unknown host. Also reject
  // backslash-normalised variants (\\evil.com → //evil.com) because
  // browsers treat backslash as a path separator in URLs.
  if (/^(\/\/|\\\\)/.test(href)) {
    return false;
  }
  // Parse the href so we can inspect its scheme. Items without an explicit
  // protocol (report.md, ./report.md, ../assets/chart.png, /workspace/foo)
  // resolve relative to the dummy HTTPS base, producing an https: URL.
  // Explicitly-schemed URLs (https://…, mailto:, javascript:, data:, …)
  // keep their native scheme, which we then check against the allowlist.
  try {
    const parsed = new URL(href, "https://dummy.example/");
    return (SAFE_HREF_PROTOCOLS as ReadonlyArray<string>).includes(
      parsed.protocol,
    );
  } catch {
    return false;
  }
}

function isExternalUrl(href: string | undefined): boolean {
  if (typeof href !== "string") {
    return false;
  }
  return /^https?:\/\//.test(href);
}

/**
 * Builds the `a` renderer shared by message content and generic markdown.
 */
export function createMarkdownLinkComponent() {
  return function MarkdownLink({
    href,
    node: _node,
    ...props
  }: AnchorHTMLAttributes<HTMLAnchorElement> & ExtraProps) {
    // Reject unsafe schemes up front so a prompt-injected / pasted href can
    // never reach the rendered anchor — including Markdown links generated by the model. Keep the visible label so the user can still see what the
    // link claimed to point at.
    if (href !== undefined && !isSafeHref(href)) {
      // Intentionally no {...props} spread: react-markdown props like `node`
      // (and anchor-only attributes such as target/rel) are not valid on a
      // <span> and would trigger React DOM warnings.
      const { className, children } = props;
      return (
        <span
          className={cn(
            "text-muted-foreground cursor-not-allowed underline decoration-dotted underline-offset-2",
            className,
          )}
          aria-label="已忽略不安全链接"
          title={`无法打开此链接：${href}`}
        >
          {children}
        </span>
      );
    }
    const { className, target, rel, ...rest } = props;
    const external = isExternalUrl(href);
    return (
      <a
        {...rest}
        href={href}
        className={cn(
          "text-primary decoration-primary/30 hover:decoration-primary/60 underline underline-offset-2 transition-colors",
          className,
        )}
        target={target ?? (external ? "_blank" : undefined)}
        rel={rel ?? (external ? "noopener noreferrer" : undefined)}
      />
    );
  };
}
